{% set name = "libdai" %}
{% set version = "0.3.1" %}
{% set sha256 = "78b6cbfc23124c69dd31451974d50efd109adc0607f581738a7c357bd6689511" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: libdai-{{ version }}.tar.gz
  url: https://github.com/DerThorsten/libdai/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - boost-cpp >=1.4
    - gmp
  run:
    - gmp

test:
  commands:
    - test -d ${PREFIX}/include/dai  # [unix]
    - test -f ${PREFIX}/include/dai/alldai.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\dai\alldai.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/libdai
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'libDAI'
  description: 'libDAI'
  dev_url: https://github.com/DerThorsten/libdai

extra:
  recipe-maintainers:
    - DerThorsten
