{% set name = "qpbo_header_only" %}
{% set version = "0.3.11" %}
{% set sha256 = "d4c60d6b5da4d2eabee254fd4989129f01e6fd077fb3dfc5cf01e9e6ede5fb74" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: qpbo-{{ version }}.tar.gz
  url: https://github.com/DerThorsten/qpbo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/qpbo  # [unix]
    - test -f ${PREFIX}/include/qpbo/qpbo.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\qpbo\qpbo.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/qpbo
  license: GPL
  license_family: GPL
  license_file: LICENCE
  summary: 'Qpbo'
  description: 'Qpbo'
  dev_url: https://github.com/DerThorsten/qpbo

extra:
  recipe-maintainers:
    - DerThorsten
