{% set name = "qpbo" %}
{% set version = "0.3.12" %}
{% set sha256 = "75d6ac1a0d56e3f83cf22afba0d156c2edbdb6b31afbfe9df335b44283972fb9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: qpbo-{{ version }}.tar.gz
  url: https://github.com/DerThorsten/qpbo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/qpbo  # [unix]
    - test -f ${PREFIX}/include/qpbo/QPBO.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\qpbo\QPBO.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/qpbo
  license: GPL
  license_family: GPL
  license_file: LICENCE
  summary: 'Qpbo solver for discrete graphical models'
  description: 'Qpbo'
  dev_url: https://github.com/DerThorsten/qpbo

extra:
  recipe-maintainers:
    - DerThorsten
