{% set name = "qpbo" %}
{% set version = "1.4.2" %}
{% set sha256 = "867082a378034e5a2b6b459c42b39b457332881ce2f19846ca95ec6855aea50b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: qpbo-{{ version }}.tar.gz
  url: https://github.com/DerThorsten/qpbo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/qpbo  # [unix]
    - test -f ${PREFIX}/include/qpbo/qpbo.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\qpbo\qpbo.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/qpbo
  license: GPL
  license_family: GPL
  license_file: LICENCE
  summary: 'a header only version of Qpbo/ Qpbo solver for discrete graphical models'
  description: 'a header only version of Qpbo/ Qpbo solver for discrete graphical models'
  dev_url: https://github.com/DerThorsten/qpbo

extra:
  recipe-maintainers:
    - DerThorsten
