{% set name = "ad3" %}
{% set version = "2.5.3" %}
{% set sha256 = "1a63e2e401a33467febc22ca10e91d7385c6813b2c3b44e96460360b76db147c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: ad3-{{ version }}.tar.gz
  url: https://github.com/DerThorsten/AD3/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/ad3  # [unix]
    - test -f ${PREFIX}/include/ad3/Factor.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\ad3\Factor.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DerThorsten/AD3
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: 'AD3s'
  description: 'AD3s'
  documentation_url:  https://github.com/DerThorsten/AD3
  dev_url: https://github.com/DerThorsten/AD3

extra:
  recipe-maintainers:
    - DerThorsten
